version: 2.1

jobs:
  training:
    machine:
      resource_class: gpu.nvidia.medium
      image: linux-cuda-11:default
    steps:
      - checkout
      - run:
          name: Check GPU status
          command: nvidia-smi
      - run:
          name: Set up MaskDataSet from ROBOFLOW (needs registration)
          command: |
            mkdir MaskDataSet
            cd MaskDataSet
            curl -L "https://universe.roboflow.com/ds/3ngtg3QH0C?key=$ROBOFLOW_KEY" > roboflow.zip; unzip roboflow.zip; rm roboflow.zip                        

workflows:
  mask_detection_training:
    jobs:
      - training:
          context:
            - docker
